grafana:
  enabled: false
kubeApiServer:
  enabled: false
kubeScheduler:
  enabled: false
namespaceOverride: monitoring
alertmanager:
  ingress:
    enabled: true
    hosts:
      - alertmanager.FIXME
    ingressClassName: internal
    tls:
      - secretName: alertmanager-tls
        hosts:
          - alertmanager.FIXME
prometheus:
  ingress:
    enabled: true
    hosts:
      - prometheus.FIXME
    ingressClassName: internal
    tls:
      - secretName: prometheus-tls
        hosts:
          - prometheus.FIXME
