resources:
  - charts/kube-state-metrics/templates/podsecuritypolicy.yaml
  - charts/kube-state-metrics/templates/deployment.yaml
  - charts/kube-state-metrics/templates/role.yaml
  - charts/kube-state-metrics/templates/psp-clusterrole.yaml
  - charts/kube-state-metrics/templates/service.yaml
  - charts/kube-state-metrics/templates/serviceaccount.yaml
  - charts/kube-state-metrics/templates/clusterrolebinding.yaml
  - charts/kube-state-metrics/templates/psp-clusterrolebinding.yaml
  - charts/prometheus-node-exporter/templates/daemonset.yaml
  - charts/prometheus-node-exporter/templates/psp-clusterrole.yaml
  - charts/prometheus-node-exporter/templates/service.yaml
  - charts/prometheus-node-exporter/templates/serviceaccount.yaml
  - charts/prometheus-node-exporter/templates/psp.yaml
  - charts/prometheus-node-exporter/templates/psp-clusterrolebinding.yaml
  - templates/alertmanager/servicemonitor.yaml
  - templates/alertmanager/alertmanager.yaml
  - templates/alertmanager/ingress.yaml
  - templates/alertmanager/service.yaml
  - templates/alertmanager/psp-rolebinding.yaml
  - templates/alertmanager/serviceaccount.yaml
  - templates/alertmanager/psp.yaml
  - templates/alertmanager/secret.yaml
  - templates/alertmanager/psp-role.yaml
  - templates/exporters/kube-state-metrics/serviceMonitor.yaml
  - templates/exporters/kube-etcd/servicemonitor.yaml
  - templates/exporters/kube-etcd/service.yaml
  - templates/exporters/kube-controller-manager/servicemonitor.yaml
  - templates/exporters/kube-controller-manager/service.yaml
  - templates/exporters/core-dns/servicemonitor.yaml
  - templates/exporters/core-dns/service.yaml
  - templates/exporters/kubelet/servicemonitor.yaml
  - templates/exporters/kube-proxy/servicemonitor.yaml
  - templates/exporters/kube-proxy/service.yaml
  - templates/exporters/node-exporter/servicemonitor.yaml
  - templates/prometheus-operator/servicemonitor.yaml
  - templates/prometheus-operator/deployment.yaml
  - templates/prometheus-operator/psp-clusterrole.yaml
  - templates/prometheus-operator/service.yaml
  - templates/prometheus-operator/clusterrole.yaml
  - templates/prometheus-operator/serviceaccount.yaml
  - templates/prometheus-operator/psp.yaml
  - templates/prometheus-operator/clusterrolebinding.yaml
  - templates/prometheus-operator/admission-webhooks/validatingWebhookConfiguration.yaml
  - templates/prometheus-operator/admission-webhooks/job-patch/role.yaml
  - templates/prometheus-operator/admission-webhooks/job-patch/job-createSecret.yaml
  - templates/prometheus-operator/admission-webhooks/job-patch/job-patchWebhook.yaml
  - templates/prometheus-operator/admission-webhooks/job-patch/clusterrole.yaml
  - templates/prometheus-operator/admission-webhooks/job-patch/serviceaccount.yaml
  - templates/prometheus-operator/admission-webhooks/job-patch/psp.yaml
  - templates/prometheus-operator/admission-webhooks/job-patch/clusterrolebinding.yaml
  - templates/prometheus-operator/admission-webhooks/job-patch/rolebinding.yaml
  - templates/prometheus-operator/admission-webhooks/mutatingWebhookConfiguration.yaml
  - templates/prometheus-operator/psp-clusterrolebinding.yaml
  - templates/prometheus/servicemonitor.yaml
  - templates/prometheus/psp-clusterrole.yaml
  - templates/prometheus/ingress.yaml
  - templates/prometheus/prometheus.yaml
  - templates/prometheus/service.yaml
  - templates/prometheus/clusterrole.yaml
  - templates/prometheus/rules-1.14/kubernetes-system-controller-manager.yaml
  - templates/prometheus/rules-1.14/kube-prometheus-general.rules.yaml
  - templates/prometheus/rules-1.14/prometheus-operator.yaml
  - templates/prometheus/rules-1.14/kubernetes-resources.yaml
  - templates/prometheus/rules-1.14/kube-state-metrics.yaml
  - templates/prometheus/rules-1.14/kubernetes-apps.yaml
  - templates/prometheus/rules-1.14/etcd.yaml
  - templates/prometheus/rules-1.14/general.rules.yaml
  - templates/prometheus/rules-1.14/prometheus.yaml
  - templates/prometheus/rules-1.14/kubelet.rules.yaml
  - templates/prometheus/rules-1.14/kube-apiserver-histogram.rules.yaml
  - templates/prometheus/rules-1.14/node.rules.yaml
  - templates/prometheus/rules-1.14/alertmanager.rules.yaml
  - templates/prometheus/rules-1.14/kube-prometheus-node-recording.rules.yaml
  - templates/prometheus/rules-1.14/kubernetes-system.yaml
  - templates/prometheus/rules-1.14/node-exporter.rules.yaml
  - templates/prometheus/rules-1.14/node-network.yaml
  - templates/prometheus/rules-1.14/node-exporter.yaml
  - templates/prometheus/rules-1.14/kubernetes-system-apiserver.yaml
  - templates/prometheus/rules-1.14/k8s.rules.yaml
  - templates/prometheus/rules-1.14/kubernetes-system-kubelet.yaml
  - templates/prometheus/rules-1.14/kube-apiserver-burnrate.rules.yaml
  - templates/prometheus/rules-1.14/kubernetes-storage.yaml
  - templates/prometheus/serviceaccount.yaml
  - templates/prometheus/psp.yaml
  - templates/prometheus/clusterrolebinding.yaml
  - templates/prometheus/psp-clusterrolebinding.yaml
