---
# Source: kube-prometheus-stack/charts/prometheus-node-exporter/templates/psp-clusterrole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: psp-prometheus-prometheus-node-exporter
  labels:     
    app: prometheus-node-exporter
    heritage: Helm
    release: prometheus
    chart: prometheus-node-exporter-2.0.4
    jobLabel: node-exporter
rules:
- apiGroups: ['extensions']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - prometheus-prometheus-node-exporter
