---
# Source: kube-prometheus-stack/charts/prometheus-node-exporter/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-prometheus-node-exporter
  namespace: monitoring
  labels:
    app: prometheus-node-exporter
    chart: prometheus-node-exporter-2.0.4
    release: "prometheus"
    heritage: "Helm"
  annotations:
    {}
imagePullSecrets:
  []
